<a href="https://colab.research.google.com/github/annagradziel12/rozne_zrodla_danych/blob/master/Excel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
pd.read_excel("file_example_XLSX_10.xlsx")

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

# Wczytujemy pierwszy arkusz

* wczytujemy arkusz "ogółem"
* pomijamy pierwsze dwa wiersze (nagłówek)
* pomijamy ostatni wiersz (RAZEM)
* usuwamy kolumnę A (kody placówek oświatowych)
* nazwy placówek oświatowych mają być indeksem

In [ ]:
# conda install xlrd # opcjonalnie jak komuś nie działa

Jak poznać nazwy arkuszy?

In [ ]:
xl = pd.ExcelFile('WypadkiwgwojewodztwIX2016.xls')
xl.sheet_names

['ogółem',
 'wg województw',
 'rodzaj zajęć',
 'przyczyny',
 'miejsce',
 'rodzaj uszkodzenia',
 'część ciała']

In [ ]:
xl.parse("ogółem")

,Wypadki w szkołach i placówkach w roku szkolnym 2015/2016 wg SIO stan na 30.09.2016 r.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,ciężki,inny,śmiertelny,Razem
2,00001,Przedszkole,10,2228,0,2238
3,00003,Szkoła podstawowa,62,30737,0,30799
4,00004,Gimnazjum,53,21513,4,21570
5,00013,Zasadnicza szkoła zawodowa,0,1077,1,1078
6,00014,Liceum ogólnokształcące,13,4666,0,4679
7,00016,Technikum,6,4031,0,4037
8,00019,Szkoła policealna (ponadgimnazjalna),0,51,0,51
9,00020,Szkoła specjalna przysposabiająca do pracy dla...,1,55,0,56
10,00021,Sześcioletnia ogólnokształcąca szkoła muzyczna...,0,99,0,99
11,00022,Sześcioletnia szkoła muzyczna I stopnia,0,1,0,1
12,00023,Czteroletnia szkoła muzyczna I stopnia,0,1,0,1
13,00024,Sześcioletnia ogólnokształcąca szkoła muzyczna...,0,19,0,19
14,00026,Sześcioletnia ogólnokształcąca szkoła sztuk pi...,0,29,0,29
15,00027,Czteroletnie liceum plastyczne,0,30,0,30
16,00029,Dziewięcioletnia ogólnokształcąca szkoła baletowa,0,20,0,20
17,00031,Czteroletnia szkoła sztuki cyrkowej,0,1,0,1
18,00037,Pałac młodzieży,0,10,0,10
19,00038,Młodzieżowy dom kultury,0,26,0,26
20,00039,Ognisko pracy pozaszkolnej,0,3,0,3
21,00040,Międzyszkolny ośrodek sportowy,0,19,0,19
22,00041,Ogród jordanowski,0,1,0,1
23,00042,Pozaszkolna placówka specjalistyczna,0,1,0,1
24,00045,Centrum Kształcenia Praktycznego,0,34,0,34
25,00046,Centrum Kształcenia Ustawicznego ze szkołami,0,8,0,8
26,00047,Ośrodek dokształcania i doskonalenia zawodowego,0,7,0,7
27,00050,Specjalny Ośrodek Wychowawczy,0,5,0,5
28,00051,Specjalny Ośrodek Szkolno-Wychowawczy,0,89,0,89
29,00052,Ośrodek Rewalidacyjno-Wychowawczy umożliwiając...,0,12,0,12
30,00053,Młodzieżowy Ośrodek Wychowawczy,3,85,0,88
31,00054,Młodzieżowy Ośrodek Socjoterapii ze szkołami,3,60,0,63
32,00055,Bursa,0,51,0,51
33,00056,Dom wczasów dziecięcych,0,75,0,75
34,00064,Niepubliczna placówka oświatowo-wychowawcza w ...,0,3,0,3
35,00080,Zespół wychowania przedszkolnego,0,1,0,1
36,00081,Punkt przedszkolny,0,26,0,26
37,00082,Poznańska szkoła chóralna,0,10,0,10
38,00090,Bednarska Szkoła Realna,0,1,0,1
39,Razem,NaN,151,65085,5,65241

In [ ]:
wypadki = pd.read_excel("WypadkiwgwojewodztwIX2016.xls",
                        sheet_name="ogółem", 
                        header=2, 
                        index_col=0, 
                        skipfooter=1, 
                        usecols="B:F")
wypadki

,ciężki,inny,śmiertelny,Razem
Przedszkole,10,2228,0,2238
Szkoła podstawowa,62,30737,0,30799
Gimnazjum,53,21513,4,21570
Zasadnicza szkoła zawodowa,0,1077,1,1078
Liceum ogólnokształcące,13,4666,0,4679
Technikum,6,4031,0,4037
Szkoła policealna (ponadgimnazjalna),0,51,0,51
Szkoła specjalna przysposabiająca do pracy dla uczniów z upośledzeniem umysłowym w stopniu umiarkowanym lub znacznym oraz dla uczniów z więcej niż jedną niepełnosprawnością,1,55,0,56
Sześcioletnia ogólnokształcąca szkoła muzyczna I stopnia,0,99,0,99
Sześcioletnia szkoła muzyczna I stopnia,0,1,0,1
Czteroletnia szkoła muzyczna I stopnia,0,1,0,1
Sześcioletnia ogólnokształcąca szkoła muzyczna II stopnia,0,19,0,19
Sześcioletnia ogólnokształcąca szkoła sztuk pięknych,0,29,0,29
Czteroletnie liceum plastyczne,0,30,0,30
Dziewięcioletnia ogólnokształcąca szkoła baletowa,0,20,0,20
Czteroletnia szkoła sztuki cyrkowej,0,1,0,1
Pałac młodzieży,0,10,0,10
Młodzieżowy dom kultury,0,26,0,26
Ognisko pracy pozaszkolnej,0,3,0,3
Międzyszkolny ośrodek sportowy,0,19,0,19
Ogród jordanowski,0,1,0,1
Pozaszkolna placówka specjalistyczna,0,1,0,1
Centrum Kształcenia Praktycznego,0,34,0,34
Centrum Kształcenia Ustawicznego ze szkołami,0,8,0,8
Ośrodek dokształcania i doskonalenia zawodowego,0,7,0,7
Specjalny Ośrodek Wychowawczy,0,5,0,5
Specjalny Ośrodek Szkolno-Wychowawczy,0,89,0,89
Ośrodek Rewalidacyjno-Wychowawczy umożliwiający upośledzonym umysłowo realizację obowiązku szkolnego i nauki,0,12,0,12
Młodzieżowy Ośrodek Wychowawczy,3,85,0,88
Młodzieżowy Ośrodek Socjoterapii ze szkołami,3,60,0,63
Bursa,0,51,0,51
Dom wczasów dziecięcych,0,75,0,75
Niepubliczna placówka oświatowo-wychowawcza w systemie oświaty,0,3,0,3
Zespół wychowania przedszkolnego,0,1,0,1
Punkt przedszkolny,0,26,0,26
Poznańska szkoła chóralna,0,10,0,10
Bednarska Szkoła Realna,0,1,0,1

In [ ]:
pd.read_excel("WypadkiwgwojewodztwIX2016.xls",
              sheet_name = "ogółem",
              skiprows=2, 
              skipfooter=1,
              usecols = "B:Z",
              index_col = 0)

,ciężki,inny,śmiertelny,Razem
Przedszkole,10,2228,0,2238
Szkoła podstawowa,62,30737,0,30799
Gimnazjum,53,21513,4,21570
Zasadnicza szkoła zawodowa,0,1077,1,1078
Liceum ogólnokształcące,13,4666,0,4679
Technikum,6,4031,0,4037
Szkoła policealna (ponadgimnazjalna),0,51,0,51
Szkoła specjalna przysposabiająca do pracy dla uczniów z upośledzeniem umysłowym w stopniu umiarkowanym lub znacznym oraz dla uczniów z więcej niż jedną niepełnosprawnością,1,55,0,56
Sześcioletnia ogólnokształcąca szkoła muzyczna I stopnia,0,99,0,99
Sześcioletnia szkoła muzyczna I stopnia,0,1,0,1
Czteroletnia szkoła muzyczna I stopnia,0,1,0,1
Sześcioletnia ogólnokształcąca szkoła muzyczna II stopnia,0,19,0,19
Sześcioletnia ogólnokształcąca szkoła sztuk pięknych,0,29,0,29
Czteroletnie liceum plastyczne,0,30,0,30
Dziewięcioletnia ogólnokształcąca szkoła baletowa,0,20,0,20
Czteroletnia szkoła sztuki cyrkowej,0,1,0,1
Pałac młodzieży,0,10,0,10
Młodzieżowy dom kultury,0,26,0,26
Ognisko pracy pozaszkolnej,0,3,0,3
Międzyszkolny ośrodek sportowy,0,19,0,19
Ogród jordanowski,0,1,0,1
Pozaszkolna placówka specjalistyczna,0,1,0,1
Centrum Kształcenia Praktycznego,0,34,0,34
Centrum Kształcenia Ustawicznego ze szkołami,0,8,0,8
Ośrodek dokształcania i doskonalenia zawodowego,0,7,0,7
Specjalny Ośrodek Wychowawczy,0,5,0,5
Specjalny Ośrodek Szkolno-Wychowawczy,0,89,0,89
Ośrodek Rewalidacyjno-Wychowawczy umożliwiający upośledzonym umysłowo realizację obowiązku szkolnego i nauki,0,12,0,12
Młodzieżowy Ośrodek Wychowawczy,3,85,0,88
Młodzieżowy Ośrodek Socjoterapii ze szkołami,3,60,0,63
Bursa,0,51,0,51
Dom wczasów dziecięcych,0,75,0,75
Niepubliczna placówka oświatowo-wychowawcza w systemie oświaty,0,3,0,3
Zespół wychowania przedszkolnego,0,1,0,1
Punkt przedszkolny,0,26,0,26
Poznańska szkoła chóralna,0,10,0,10
Bednarska Szkoła Realna,0,1,0,1

In [ ]:
pd.read_excel("WypadkiwgwojewodztwIX2016.xls",
              sheet_name = "ogółem",
              skiprows=2, 
              skipfooter=1,
              usecols = "B:Z",
              index_col = 0)

,ciężki,inny,śmiertelny,Razem
Przedszkole,10,2228,0,2238
Szkoła podstawowa,62,30737,0,30799
Gimnazjum,53,21513,4,21570
Zasadnicza szkoła zawodowa,0,1077,1,1078
Liceum ogólnokształcące,13,4666,0,4679
Technikum,6,4031,0,4037
Szkoła policealna (ponadgimnazjalna),0,51,0,51
Szkoła specjalna przysposabiająca do pracy dla uczniów z upośledzeniem umysłowym w stopniu umiarkowanym lub znacznym oraz dla uczniów z więcej niż jedną niepełnosprawnością,1,55,0,56
Sześcioletnia ogólnokształcąca szkoła muzyczna I stopnia,0,99,0,99
Sześcioletnia szkoła muzyczna I stopnia,0,1,0,1
Czteroletnia szkoła muzyczna I stopnia,0,1,0,1
Sześcioletnia ogólnokształcąca szkoła muzyczna II stopnia,0,19,0,19
Sześcioletnia ogólnokształcąca szkoła sztuk pięknych,0,29,0,29
Czteroletnie liceum plastyczne,0,30,0,30
Dziewięcioletnia ogólnokształcąca szkoła baletowa,0,20,0,20
Czteroletnia szkoła sztuki cyrkowej,0,1,0,1
Pałac młodzieży,0,10,0,10
Młodzieżowy dom kultury,0,26,0,26
Ognisko pracy pozaszkolnej,0,3,0,3
Międzyszkolny ośrodek sportowy,0,19,0,19
Ogród jordanowski,0,1,0,1
Pozaszkolna placówka specjalistyczna,0,1,0,1
Centrum Kształcenia Praktycznego,0,34,0,34
Centrum Kształcenia Ustawicznego ze szkołami,0,8,0,8
Ośrodek dokształcania i doskonalenia zawodowego,0,7,0,7
Specjalny Ośrodek Wychowawczy,0,5,0,5
Specjalny Ośrodek Szkolno-Wychowawczy,0,89,0,89
Ośrodek Rewalidacyjno-Wychowawczy umożliwiający upośledzonym umysłowo realizację obowiązku szkolnego i nauki,0,12,0,12
Młodzieżowy Ośrodek Wychowawczy,3,85,0,88
Młodzieżowy Ośrodek Socjoterapii ze szkołami,3,60,0,63
Bursa,0,51,0,51
Dom wczasów dziecięcych,0,75,0,75
Niepubliczna placówka oświatowo-wychowawcza w systemie oświaty,0,3,0,3
Zespół wychowania przedszkolnego,0,1,0,1
Punkt przedszkolny,0,26,0,26
Poznańska szkoła chóralna,0,10,0,10
Bednarska Szkoła Realna,0,1,0,1

# Wczytujemy arkusz "wg województw"

* pomijamy kolumny z numerami identyfikacyjnymi placówek oświatowych i województw
* chcemy mieć inaczej zgrupowane dane: najpierw duża, zewnętrzna grupa "przedszkole" a potem wyszczególnione województwa

In [ ]:
wypadki2 = pd.read_excel("WypadkiwgwojewodztwIX2016.xls",
                         sheet_name="wg województw", 
                         header=2, 
                         index_col=[1,0], 
                         skipfooter=1, 
                         usecols="B,D:Q")
wypadki2.sort_index(axis=0, level=0, inplace=True)
wypadki2

                                                          ciężki  inny  \
Bednarska Szkoła Realna          WOJ. MAZOWIECKIE              0     1
Bursa                            WOJ. DOLNOŚLĄSKIE             0     4
                                 WOJ. KUJAWSKO-POMORSKIE       0     1
                                 WOJ. LUBELSKIE                0    10
                                 WOJ. MAŁOPOLSKIE              0    14
...                                                          ...   ...
Zasadnicza szkoła zawodowa       WOJ. ZACHODNIOPOMORSKIE       0    48
                                 WOJ. ŁÓDZKIE                  0    49
                                 WOJ. ŚLĄSKIE                  0   175
                                 WOJ. ŚWIĘTOKRZYSKIE           0    30
Zespół wychowania przedszkolnego WOJ. POMORSKIE                0     1

                                                          śmiertelny  Razem
Bednarska Szkoła Realna          WOJ. MAZOWIECKIE                  0      1
Bursa                            WOJ. DOLNOŚLĄSKIE                 0      4
                                 WOJ. KUJAWSKO-POMORSKIE           0      1
                                 WOJ. LUBELSKIE                    0     10
                                 WOJ. MAŁOPOLSKIE                  0     14
...                                                              ...    ...
Zasadnicza szkoła zawodowa       WOJ. ZACHODNIOPOMORSKIE           0     48
                                 WOJ. ŁÓDZKIE                      0     49
                                 WOJ. ŚLĄSKIE                      0    175
                                 WOJ. ŚWIĘTOKRZYSKIE               0     30
Zespół wychowania przedszkolnego WOJ. POMORSKIE                    0      1

[273 rows x 4 columns]